// Copyright 2021-2025 NCSDecomp
// Licensed under the Business Source License 1.1 (BSL 1.1).
// See LICENSE.txt file in the project root for full license information.

package com.kotor.resource.formats.ncs.parser;

import com.kotor.resource.formats.ncs.analysis.AnalysisAdapter;
import com.kotor.resource.formats.ncs.node.EOF;
import com.kotor.resource.formats.ncs.node.TAction;
import com.kotor.resource.formats.ncs.node.TAdd;
import com.kotor.resource.formats.ncs.node.TBoolandii;
import com.kotor.resource.formats.ncs.node.TComp;
import com.kotor.resource.formats.ncs.node.TConst;
import com.kotor.resource.formats.ncs.node.TCpdownbp;
import com.kotor.resource.formats.ncs.node.TCpdownsp;
import com.kotor.resource.formats.ncs.node.TCptopbp;
import com.kotor.resource.formats.ncs.node.TCptopsp;
import com.kotor.resource.formats.ncs.node.TDecibp;
import com.kotor.resource.formats.ncs.node.TDecisp;
import com.kotor.resource.formats.ncs.node.TDestruct;
import com.kotor.resource.formats.ncs.node.TDiv;
import com.kotor.resource.formats.ncs.node.TDot;
import com.kotor.resource.formats.ncs.node.TEqual;
import com.kotor.resource.formats.ncs.node.TExcorii;
import com.kotor.resource.formats.ncs.node.TFloatConstant;
import com.kotor.resource.formats.ncs.node.TGeq;
import com.kotor.resource.formats.ncs.node.TGt;
import com.kotor.resource.formats.ncs.node.TIncibp;
import com.kotor.resource.formats.ncs.node.TIncisp;
import com.kotor.resource.formats.ncs.node.TIncorii;
import com.kotor.resource.formats.ncs.node.TIntegerConstant;
import com.kotor.resource.formats.ncs.node.TJmp;
import com.kotor.resource.formats.ncs.node.TJnz;
import com.kotor.resource.formats.ncs.node.TJsr;
import com.kotor.resource.formats.ncs.node.TJz;
import com.kotor.resource.formats.ncs.node.TLPar;
import com.kotor.resource.formats.ncs.node.TLeq;
import com.kotor.resource.formats.ncs.node.TLogandii;
import com.kotor.resource.formats.ncs.node.TLogorii;
import com.kotor.resource.formats.ncs.node.TLt;
import com.kotor.resource.formats.ncs.node.TMod;
import com.kotor.resource.formats.ncs.node.TMovsp;
import com.kotor.resource.formats.ncs.node.TMul;
import com.kotor.resource.formats.ncs.node.TNeg;
import com.kotor.resource.formats.ncs.node.TNequal;
import com.kotor.resource.formats.ncs.node.TNop;
import com.kotor.resource.formats.ncs.node.TNot;
import com.kotor.resource.formats.ncs.node.TRPar;
import com.kotor.resource.formats.ncs.node.TRestorebp;
import com.kotor.resource.formats.ncs.node.TRetn;
import com.kotor.resource.formats.ncs.node.TRsadd;
import com.kotor.resource.formats.ncs.node.TSavebp;
import com.kotor.resource.formats.ncs.node.TSemi;
import com.kotor.resource.formats.ncs.node.TShleft;
import com.kotor.resource.formats.ncs.node.TShright;
import com.kotor.resource.formats.ncs.node.TStorestate;
import com.kotor.resource.formats.ncs.node.TStringLiteral;
import com.kotor.resource.formats.ncs.node.TSub;
import com.kotor.resource.formats.ncs.node.TT;
import com.kotor.resource.formats.ncs.node.TUnright;

/**
 * Maps token types to numeric indices for parser table lookups.
 * Generated by SableCC; methods are simple setters of the index field.
 */
class TokenIndex extends AnalysisAdapter {
   int index;

   @Override
   public void caseTLPar(TLPar node) {
      this.index = 0;
   }

   @Override
   public void caseTRPar(TRPar node) {
      this.index = 1;
   }

   @Override
   public void caseTSemi(TSemi node) {
      this.index = 2;
   }

   @Override
   public void caseTDot(TDot node) {
      this.index = 3;
   }

   @Override
   public void caseTCpdownsp(TCpdownsp node) {
      this.index = 4;
   }

   @Override
   public void caseTRsadd(TRsadd node) {
      this.index = 5;
   }

   @Override
   public void caseTCptopsp(TCptopsp node) {
      this.index = 6;
   }

   @Override
   public void caseTConst(TConst node) {
      this.index = 7;
   }

   @Override
   public void caseTAction(TAction node) {
      this.index = 8;
   }

   @Override
   public void caseTLogandii(TLogandii node) {
      this.index = 9;
   }

   @Override
   public void caseTLogorii(TLogorii node) {
      this.index = 10;
   }

   @Override
   public void caseTIncorii(TIncorii node) {
      this.index = 11;
   }

   @Override
   public void caseTExcorii(TExcorii node) {
      this.index = 12;
   }

   @Override
   public void caseTBoolandii(TBoolandii node) {
      this.index = 13;
   }

   @Override
   public void caseTEqual(TEqual node) {
      this.index = 14;
   }

   @Override
   public void caseTNequal(TNequal node) {
      this.index = 15;
   }

   @Override
   public void caseTGeq(TGeq node) {
      this.index = 16;
   }

   @Override
   public void caseTGt(TGt node) {
      this.index = 17;
   }

   @Override
   public void caseTLt(TLt node) {
      this.index = 18;
   }

   @Override
   public void caseTLeq(TLeq node) {
      this.index = 19;
   }

   @Override
   public void caseTShleft(TShleft node) {
      this.index = 20;
   }

   @Override
   public void caseTShright(TShright node) {
      this.index = 21;
   }

   @Override
   public void caseTUnright(TUnright node) {
      this.index = 22;
   }

   @Override
   public void caseTAdd(TAdd node) {
      this.index = 23;
   }

   @Override
   public void caseTSub(TSub node) {
      this.index = 24;
   }

   @Override
   public void caseTMul(TMul node) {
      this.index = 25;
   }

   @Override
   public void caseTDiv(TDiv node) {
      this.index = 26;
   }

   @Override
   public void caseTMod(TMod node) {
      this.index = 27;
   }

   @Override
   public void caseTNeg(TNeg node) {
      this.index = 28;
   }

   @Override
   public void caseTComp(TComp node) {
      this.index = 29;
   }

   @Override
   public void caseTMovsp(TMovsp node) {
      this.index = 30;
   }

   @Override
   public void caseTJmp(TJmp node) {
      this.index = 31;
   }

   @Override
   public void caseTJsr(TJsr node) {
      this.index = 32;
   }

   @Override
   public void caseTJz(TJz node) {
      this.index = 33;
   }

   @Override
   public void caseTRetn(TRetn node) {
      this.index = 34;
   }

   @Override
   public void caseTDestruct(TDestruct node) {
      this.index = 35;
   }

   @Override
   public void caseTNot(TNot node) {
      this.index = 36;
   }

   @Override
   public void caseTDecisp(TDecisp node) {
      this.index = 37;
   }

   @Override
   public void caseTIncisp(TIncisp node) {
      this.index = 38;
   }

   @Override
   public void caseTJnz(TJnz node) {
      this.index = 39;
   }

   @Override
   public void caseTCpdownbp(TCpdownbp node) {
      this.index = 40;
   }

   @Override
   public void caseTCptopbp(TCptopbp node) {
      this.index = 41;
   }

   @Override
   public void caseTDecibp(TDecibp node) {
      this.index = 42;
   }

   @Override
   public void caseTIncibp(TIncibp node) {
      this.index = 43;
   }

   @Override
   public void caseTSavebp(TSavebp node) {
      this.index = 44;
   }

   @Override
   public void caseTRestorebp(TRestorebp node) {
      this.index = 45;
   }

   @Override
   public void caseTStorestate(TStorestate node) {
      this.index = 46;
   }

   @Override
   public void caseTNop(TNop node) {
      this.index = 47;
   }

   @Override
   public void caseTT(TT node) {
      this.index = 48;
   }

   @Override
   public void caseTStringLiteral(TStringLiteral node) {
      this.index = 49;
   }

   @Override
   public void caseTIntegerConstant(TIntegerConstant node) {
      this.index = 50;
   }

   @Override
   public void caseTFloatConstant(TFloatConstant node) {
      this.index = 51;
   }

   @Override
   public void caseEOF(EOF node) {
      this.index = 52;
   }
}

