// Copyright 2021-2025 NCSDecomp
// Licensed under the Business Source License 1.1 (BSL 1.1).
// See LICENSE.txt file in the project root for full license information.

package com.kotor.resource.formats.ncs.node;

import com.kotor.resource.formats.ncs.analysis.Analysis;

/**
 * AST node representing an ACTION opcode with full metadata:
 * <ul>
 *   <li>{@link #_action_}: terminal token "ACTION"</li>
 *   <li>{@link #_pos_}: bytecode position</li>
 *   <li>{@link #_type_}: return type code</li>
 *   <li>{@link #_id_}: action ID (index into actions table)</li>
 *   <li>{@link #_argCount_}: number of arguments that follow</li>
 *   <li>{@link #_semi_}: trailing semicolon token</li>
 * </ul>
 * Generated by SableCC; identifiers retained for parser compatibility.
 */
public final class AActionCommand extends PActionCommand {
   private TAction _action_;
   private TIntegerConstant _pos_;
   private TIntegerConstant _type_;
   private TIntegerConstant _id_;
   private TIntegerConstant _argCount_;
   private TSemi _semi_;

   public AActionCommand() {
   }

   public AActionCommand(TAction _action_, TIntegerConstant _pos_, TIntegerConstant _type_, TIntegerConstant _id_, TIntegerConstant _argCount_, TSemi _semi_) {
      this.setAction(_action_);
      this.setPos(_pos_);
      this.setType(_type_);
      this.setId(_id_);
      this.setArgCount(_argCount_);
      this.setSemi(_semi_);
   }

   @Override
   public Object clone() {
      return new AActionCommand(
         (TAction)this.cloneNode(this._action_),
         (TIntegerConstant)this.cloneNode(this._pos_),
         (TIntegerConstant)this.cloneNode(this._type_),
         (TIntegerConstant)this.cloneNode(this._id_),
         (TIntegerConstant)this.cloneNode(this._argCount_),
         (TSemi)this.cloneNode(this._semi_)
      );
   }

   @Override
   public void apply(Switch sw) {
      ((Analysis)sw).caseAActionCommand(this);
   }

   public TAction getAction() {
      return this._action_;
   }

   public void setAction(TAction node) {
      if (this._action_ != null) {
         this._action_.parent(null);
      }

      if (node != null) {
         if (node.parent() != null) {
            node.parent().removeChild(node);
         }

         node.parent(this);
      }

      this._action_ = node;
   }

   public TIntegerConstant getPos() {
      return this._pos_;
   }

   public void setPos(TIntegerConstant node) {
      if (this._pos_ != null) {
         this._pos_.parent(null);
      }

      if (node != null) {
         if (node.parent() != null) {
            node.parent().removeChild(node);
         }

         node.parent(this);
      }

      this._pos_ = node;
   }

   public TIntegerConstant getType() {
      return this._type_;
   }

   public void setType(TIntegerConstant node) {
      if (this._type_ != null) {
         this._type_.parent(null);
      }

      if (node != null) {
         if (node.parent() != null) {
            node.parent().removeChild(node);
         }

         node.parent(this);
      }

      this._type_ = node;
   }

   public TIntegerConstant getId() {
      return this._id_;
   }

   public void setId(TIntegerConstant node) {
      if (this._id_ != null) {
         this._id_.parent(null);
      }

      if (node != null) {
         if (node.parent() != null) {
            node.parent().removeChild(node);
         }

         node.parent(this);
      }

      this._id_ = node;
   }

   public TIntegerConstant getArgCount() {
      return this._argCount_;
   }

   public void setArgCount(TIntegerConstant node) {
      if (this._argCount_ != null) {
         this._argCount_.parent(null);
      }

      if (node != null) {
         if (node.parent() != null) {
            node.parent().removeChild(node);
         }

         node.parent(this);
      }

      this._argCount_ = node;
   }

   public TSemi getSemi() {
      return this._semi_;
   }

   public void setSemi(TSemi node) {
      if (this._semi_ != null) {
         this._semi_.parent(null);
      }

      if (node != null) {
         if (node.parent() != null) {
            node.parent().removeChild(node);
         }

         node.parent(this);
      }

      this._semi_ = node;
   }

   @Override
   public String toString() {
      return this.toString(this._action_)
         + this.toString(this._pos_)
         + this.toString(this._type_)
         + this.toString(this._id_)
         + this.toString(this._argCount_)
         + this.toString(this._semi_);
   }

   @Override
   void removeChild(Node child) {
      if (this._action_ == child) {
         this._action_ = null;
      } else if (this._pos_ == child) {
         this._pos_ = null;
      } else if (this._type_ == child) {
         this._type_ = null;
      } else if (this._id_ == child) {
         this._id_ = null;
      } else if (this._argCount_ == child) {
         this._argCount_ = null;
      } else if (this._semi_ == child) {
         this._semi_ = null;
      }
   }

   @Override
   void replaceChild(Node oldChild, Node newChild) {
      if (this._action_ == oldChild) {
         this.setAction((TAction)newChild);
      } else if (this._pos_ == oldChild) {
         this.setPos((TIntegerConstant)newChild);
      } else if (this._type_ == oldChild) {
         this.setType((TIntegerConstant)newChild);
      } else if (this._id_ == oldChild) {
         this.setId((TIntegerConstant)newChild);
      } else if (this._argCount_ == oldChild) {
         this.setArgCount((TIntegerConstant)newChild);
      } else if (this._semi_ == oldChild) {
         this.setSemi((TSemi)newChild);
      }
   }
}

