// Copyright 2021-2025 NCSDecomp
// Licensed under the Business Source License 1.1 (BSL 1.1).
// See LICENSE.txt file in the project root for full license information.

package com.kotor.resource.formats.ncs.node;

import com.kotor.resource.formats.ncs.analysis.Analysis;

/**
 * AST node representing a CONST opcode and its literal payload.
 * Fields:
 * <ul>
 *   <li>{@link #_const_}: terminal token "CONST"</li>
 *   <li>{@link #_pos_}: bytecode position</li>
 *   <li>{@link #_type_}: type code of the constant</li>
 *   <li>{@link #_constant_}: literal value (int/float/string/object)</li>
 *   <li>{@link #_semi_}: trailing semicolon token</li>
 * </ul>
 * Generated by SableCC; identifiers retained for parser compatibility.
 */
public final class AConstCommand extends PConstCommand {
   private TConst _const_;
   private TIntegerConstant _pos_;
   private TIntegerConstant _type_;
   private PConstant _constant_;
   private TSemi _semi_;

   public AConstCommand() {
   }

   public AConstCommand(TConst _const_, TIntegerConstant _pos_, TIntegerConstant _type_, PConstant _constant_, TSemi _semi_) {
      this.setConst(_const_);
      this.setPos(_pos_);
      this.setType(_type_);
      this.setConstant(_constant_);
      this.setSemi(_semi_);
   }

   @Override
   public Object clone() {
      return new AConstCommand(
         (TConst)this.cloneNode(this._const_),
         (TIntegerConstant)this.cloneNode(this._pos_),
         (TIntegerConstant)this.cloneNode(this._type_),
         (PConstant)this.cloneNode(this._constant_),
         (TSemi)this.cloneNode(this._semi_)
      );
   }

   @Override
   public void apply(Switch sw) {
      ((Analysis)sw).caseAConstCommand(this);
   }

   public TConst getConst() {
      return this._const_;
   }

   public void setConst(TConst node) {
      if (this._const_ != null) {
         this._const_.parent(null);
      }

      if (node != null) {
         if (node.parent() != null) {
            node.parent().removeChild(node);
         }

         node.parent(this);
      }

      this._const_ = node;
   }

   public TIntegerConstant getPos() {
      return this._pos_;
   }

   public void setPos(TIntegerConstant node) {
      if (this._pos_ != null) {
         this._pos_.parent(null);
      }

      if (node != null) {
         if (node.parent() != null) {
            node.parent().removeChild(node);
         }

         node.parent(this);
      }

      this._pos_ = node;
   }

   public TIntegerConstant getType() {
      return this._type_;
   }

   public void setType(TIntegerConstant node) {
      if (this._type_ != null) {
         this._type_.parent(null);
      }

      if (node != null) {
         if (node.parent() != null) {
            node.parent().removeChild(node);
         }

         node.parent(this);
      }

      this._type_ = node;
   }

   public PConstant getConstant() {
      return this._constant_;
   }

   public void setConstant(PConstant node) {
      if (this._constant_ != null) {
         this._constant_.parent(null);
      }

      if (node != null) {
         if (node.parent() != null) {
            node.parent().removeChild(node);
         }

         node.parent(this);
      }

      this._constant_ = node;
   }

   public TSemi getSemi() {
      return this._semi_;
   }

   public void setSemi(TSemi node) {
      if (this._semi_ != null) {
         this._semi_.parent(null);
      }

      if (node != null) {
         if (node.parent() != null) {
            node.parent().removeChild(node);
         }

         node.parent(this);
      }

      this._semi_ = node;
   }

   @Override
   public String toString() {
      return this.toString(this._const_) + this.toString(this._pos_) + this.toString(this._type_) + this.toString(this._constant_) + this.toString(this._semi_);
   }

   @Override
   void removeChild(Node child) {
      if (this._const_ == child) {
         this._const_ = null;
      } else if (this._pos_ == child) {
         this._pos_ = null;
      } else if (this._type_ == child) {
         this._type_ = null;
      } else if (this._constant_ == child) {
         this._constant_ = null;
      } else if (this._semi_ == child) {
         this._semi_ = null;
      }
   }

   @Override
   void replaceChild(Node oldChild, Node newChild) {
      if (this._const_ == oldChild) {
         this.setConst((TConst)newChild);
      } else if (this._pos_ == oldChild) {
         this.setPos((TIntegerConstant)newChild);
      } else if (this._type_ == oldChild) {
         this.setType((TIntegerConstant)newChild);
      } else if (this._constant_ == oldChild) {
         this.setConstant((PConstant)newChild);
      } else if (this._semi_ == oldChild) {
         this.setSemi((TSemi)newChild);
      }
   }
}

