// Copyright 2021-2025 NCSDecomp
// Licensed under the Business Source License 1.1 (BSL 1.1).
// See LICENSE.txt file in the project root for full license information.

package com.kotor.resource.formats.ncs.node;

import com.kotor.resource.formats.ncs.analysis.Analysis;

/**
 * AST node representing LOGII logical opcodes (and/or) on integers.
 * Fields:
 * <ul>
 *   <li>{@link #_logiiOp_}: specific LOGII operator token</li>
 *   <li>{@link #_pos_}: bytecode position</li>
 *   <li>{@link #_type_}: result type code</li>
 *   <li>{@link #_semi_}: trailing semicolon token</li>
 * </ul>
 * Generated by SableCC; identifiers retained for parser compatibility.
 */
public final class ALogiiCommand extends PLogiiCommand {
   private PLogiiOp _logiiOp_;
   private TIntegerConstant _pos_;
   private TIntegerConstant _type_;
   private TSemi _semi_;

   public ALogiiCommand() {
   }

   public ALogiiCommand(PLogiiOp _logiiOp_, TIntegerConstant _pos_, TIntegerConstant _type_, TSemi _semi_) {
      this.setLogiiOp(_logiiOp_);
      this.setPos(_pos_);
      this.setType(_type_);
      this.setSemi(_semi_);
   }

   @Override
   public Object clone() {
      return new ALogiiCommand(
         (PLogiiOp)this.cloneNode(this._logiiOp_),
         (TIntegerConstant)this.cloneNode(this._pos_),
         (TIntegerConstant)this.cloneNode(this._type_),
         (TSemi)this.cloneNode(this._semi_)
      );
   }

   @Override
   public void apply(Switch sw) {
      ((Analysis)sw).caseALogiiCommand(this);
   }

   public PLogiiOp getLogiiOp() {
      return this._logiiOp_;
   }

   public void setLogiiOp(PLogiiOp node) {
      if (this._logiiOp_ != null) {
         this._logiiOp_.parent(null);
      }

      if (node != null) {
         if (node.parent() != null) {
            node.parent().removeChild(node);
         }

         node.parent(this);
      }

      this._logiiOp_ = node;
   }

   public TIntegerConstant getPos() {
      return this._pos_;
   }

   public void setPos(TIntegerConstant node) {
      if (this._pos_ != null) {
         this._pos_.parent(null);
      }

      if (node != null) {
         if (node.parent() != null) {
            node.parent().removeChild(node);
         }

         node.parent(this);
      }

      this._pos_ = node;
   }

   public TIntegerConstant getType() {
      return this._type_;
   }

   public void setType(TIntegerConstant node) {
      if (this._type_ != null) {
         this._type_.parent(null);
      }

      if (node != null) {
         if (node.parent() != null) {
            node.parent().removeChild(node);
         }

         node.parent(this);
      }

      this._type_ = node;
   }

   public TSemi getSemi() {
      return this._semi_;
   }

   public void setSemi(TSemi node) {
      if (this._semi_ != null) {
         this._semi_.parent(null);
      }

      if (node != null) {
         if (node.parent() != null) {
            node.parent().removeChild(node);
         }

         node.parent(this);
      }

      this._semi_ = node;
   }

   @Override
   public String toString() {
      return this.toString(this._logiiOp_) + this.toString(this._pos_) + this.toString(this._type_) + this.toString(this._semi_);
   }

   @Override
   void removeChild(Node child) {
      if (this._logiiOp_ == child) {
         this._logiiOp_ = null;
      } else if (this._pos_ == child) {
         this._pos_ = null;
      } else if (this._type_ == child) {
         this._type_ = null;
      } else if (this._semi_ == child) {
         this._semi_ = null;
      }
   }

   @Override
   void replaceChild(Node oldChild, Node newChild) {
      if (this._logiiOp_ == oldChild) {
         this.setLogiiOp((PLogiiOp)newChild);
      } else if (this._pos_ == oldChild) {
         this.setPos((TIntegerConstant)newChild);
      } else if (this._type_ == oldChild) {
         this.setType((TIntegerConstant)newChild);
      } else if (this._semi_ == oldChild) {
         this.setSemi((TSemi)newChild);
      }
   }
}

